<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MicVolumeLock</RootNamespace>
    <AssemblyName>MicVolumeLock</AssemblyName>
    <Version>1.0.3</Version>
    <AssemblyVersion>1.0.3.0</AssemblyVersion>
    <FileVersion>1.0.3.0</FileVersion>
    <InformationalVersion>1.0.3</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <ApplicationIcon>Assets\MicVolumeLock.ico</ApplicationIcon>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>
</Project>


